package pms.inface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-07T11:52:27.850+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "WebServiceInterfaceService",
                  wsdlLocation = "http://localhost:8080/spring_webservice_server/webservice/webServiceInterface?wsdl",
                  targetNamespace = "http://spring.webservice.server")
public class WebServiceInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://spring.webservice.server", "WebServiceInterfaceService");
    public final static QName WebServiceInterfacePort = new QName("http://spring.webservice.server", "WebServiceInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring_webservice_server/webservice/webServiceInterface?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/spring_webservice_server/webservice/webServiceInterface?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WebServiceInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServiceInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServiceInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "WebServiceInterfacePort")
    public WebServiceInterface getWebServiceInterfacePort() {
        return super.getPort(WebServiceInterfacePort, WebServiceInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "WebServiceInterfacePort")
    public WebServiceInterface getWebServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(WebServiceInterfacePort, WebServiceInterface.class, features);
    }

}
