package pms.inface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-07T11:52:27.834+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://spring.webservice.server", name = "WebServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://spring.webservice.server", className = "pms.inface.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://spring.webservice.server", className = "pms.inface.SayByeResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.String sayBye(

        @WebParam(name = "word", targetNamespace = "http://spring.webservice.server")
        java.lang.String word
    );
}
