
package pms.inface;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-07T11:52:27.803+08:00
 * Generated source version: 3.3.2
 *
 */
public final class WebServiceInterface_WebServiceInterfacePort_Client {

    private static final QName SERVICE_NAME = new QName("http://spring.webservice.server", "WebServiceInterfaceService");

    private WebServiceInterface_WebServiceInterfacePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServiceInterfaceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebServiceInterfaceService ss = new WebServiceInterfaceService(wsdlURL, SERVICE_NAME);
        WebServiceInterface port = ss.getWebServiceInterfacePort();

        {
        System.out.println("Invoking sayBye...");
        java.lang.String _sayBye_word = "";
        java.lang.String _sayBye__return = port.sayBye(_sayBye_word);
        System.out.println("sayBye.result=" + _sayBye__return);


        }

        System.exit(0);
    }

}
