
package pms.inface;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-06-07T11:52:27.834+08:00
 * Generated source version: 3.3.2
 *
 */

public class WebServiceInterface_WebServiceInterfacePort_Server{

    protected WebServiceInterface_WebServiceInterfacePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WebServiceInterfacePortImpl();
        String address = "http://localhost:8080/spring_webservice_server/webservice/webServiceInterface";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new WebServiceInterface_WebServiceInterfacePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
